### ISSUE TITLE
"clear all" now gives problems

### ISSUE THREAD

**Issue by KrisThielemans** [jaeandersson/swig#47] opened 2015-09-05 23:32 UTC
"clear all" used to work (although sometimes it caused a crash). now it gives me an error if I want to use my module after the clear all

> Error using stirMATLAB_wrap
> Global type table deleted unexpectedly

**Comment by jaeandersson** [comment] 2015-09-06 09:00
Yes, I can reproduce this with CasADi:

``` matlab
import casadi.*
x = SX.sym('x');
clear all
import casadi.*
x = SX.sym('x');
```

Ping @jgillis @dcb210

**Comment by jaeandersson** [comment] 2015-09-06 09:07
Looking at the generated code, it looks like `SWIG_Matlab_LoadModule` is always called:

``` c++
void SWIG_Matlab_LoadModule(const char* name) {
    /* Initialize module if first load */
    if (!mexIsLocked()) {
      SWIG_InitializeModule(0);
    } else if (!SWIG_GetModule(0)) {
        /* Handle special case when mex is still loaded
         * and global module variable deleted.*/
        mexErrMsgIdAndTxt("SWIG:LoadFailure","Global type table deleted unexpectedly");
    }
  if(false){
    mexErrMsgIdAndTxt("SWIG:LoadFailure","Could not load module %s",name);
  }
  ...
extern "C"
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  SWIG_Matlab_LoadModule(SWIG_name_d);
  if (!mexIsLocked()) {
    mexLock();
    mexEvalString("casadisetup");
    mexAtExit(SWIG_Matlab_ExitFcn);
  }
```

I think this can be resolved by correctly using `SWIG_Matlab_ExitFcn`.

**Comment by jaeandersson** [comment] 2015-09-06 11:17
I think the reason why "clear" is currently broken can be found in the following two comments https://github.com/jaeandersson/swig/pull/43#issuecomment-137744047, https://github.com/jaeandersson/swig/pull/40#issue-103573475

In any case, not supporting "clear" is obviously unacceptable, so this has to be fixed.

**Comment by jaeandersson** [comment] 2015-09-06 15:36
I think we need to change back the handling of mexLock/mexUnlock, the current way is not good. What makes sense is to have the module freed when it is not in use anywhere. Right now, because the reference counter never reaches zero, the mex file is never deleted.

I think this can be made to work with multiple modules if one adds to the generated mex-file functions for loading and unloading modules, e.g.:

``` matlab
% get a pointer to the swig_module_info for the module and increase lock counter (e.g. call mexUnlock)
ptr = mymoduleMATLAB(0);
% decrease lock counter
mymoduleMATLAB(1);
```

This way, the use of a global variable (which will get deleted by `clean all`) can be avoided. On freeing a module, the "mexAtExit" function is called; this would have to make sure that the other modules are still valid.

**Comment by jaeandersson** [comment] 2015-09-06 16:26
@dcb210 I've reverted the changes to the mex-lock counter that caused this bug. This probably means that the module support is broken though.

**Comment by KrisThielemans** [comment] 2015-09-06 16:53
I'm out of my depth here. I can only point to a related old thread on matlabcentral
http://www.mathworks.com/matlabcentral/newsreader/view_thread/278243
which you're probably aware of anyway.

**Comment by jaeandersson** [comment] 2015-09-06 16:59
I think we already had a satisfactory solution which got broken when adding multiple module support. I think the key is to add support for multiple modules without breaking this. I'm sure that it's possible.

**Comment by jaeandersson** [comment] 2015-09-06 17:35
I've added two entry points that are intended to be used for communication directly between modules instead of using global variables.

**Comment by jaeandersson** [comment] 2015-09-06 19:40
After some investigating, I'm starting to realise that it is not easy to get this to work without global memory...

Got an idea though: might be possible to fix the "clear all" issue by replacing the global variable `swig_runtime_data_type_pointer4` with a static method inside `SwigRef`. This method would contain a persistent variable with the same information. According to MATLAB documentation, it should be possible to keep this in memory until MATLAB quits by also calling `mlock` inside the function.

**Comment by dcb210** [comment] 2015-09-07 13:16
So if I understand correctly, the problem with ‘clear all’ is that is deletes the global variable swig_runtime_data_type_pointer4?  If so, I believe there is a simple workaround.  We need only add the name of the owner of the global type table (the first module to load) to swig_runtime_data_type_pointer4 so that it can recreate the global variable again after deletion.  I’ll submit a fix sometime this week (not today).

**Comment by jaeandersson** [comment] 2015-09-08 09:27
I'm not sure if deletion of `swig_runtime_data_type_pointer4` is the only problem, but it indeed looks like `swig_runtime_data_type_pointer4` get deleted when doing `clean all`, whereas the mex-files don't get unloaded.

**Comment by jaeandersson** [comment] 2015-09-10 14:40
Should have been fixed now.

**Closed as completed by jaeandersson** 2015-09-10 14:40 UTC
Labels: bug
